//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string ISBN { get; set; }
        public string title { get; set; }
        public int yearPublished { get; set; }
        public string studentID { get; set; }
        public Nullable<int> authorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Student Student { get; set; }
    }
}
